"""Add formatting settings fields

Revision ID: 4d81eb779c86
Revises: d15294f33e99
Create Date: 2025-05-26 11:04:51.144802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d81eb779c86'
down_revision: Union[str, None] = 'd15294f33e99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applicationSettings', sa.Column('default_formatting_rules', sa.Text(), nullable=True))
    op.add_column('chatSession', sa.Column('formatting_settings', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chatSession', 'formatting_settings')
    op.drop_column('applicationSettings', 'default_formatting_rules')
    # ### end Alembic commands ###
