"""Add encrypted OpenRouter API key to ApplicationSettings

Revision ID: d15294f33e99
Revises: d8452839cce2
Create Date: 2025-05-22 10:28:50.917352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd15294f33e99'
down_revision: Union[str, None] = 'd8452839cce2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applicationSettings', sa.Column('openrouter_api_key_encrypted', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applicationSettings', 'openrouter_api_key_encrypted')
    # ### end Alembic commands ###
