"""Initial migration - create all tables

Revision ID: d8452839cce2
Revises:
Create Date: 2025-05-19 07:33:25.014779

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d8452839cce2"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "aiModel",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("label"),
    )
    op.create_table(
        "character",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("avatar_image", sa.String(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("label"),
    )
    op.create_table(
        "systemPrompt",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("label"),
    )
    op.create_table(
        "userProfile",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("avatar_image", sa.String(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("label"),
    )
    op.create_table(
        "applicationSettings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("default_ai_model_id", sa.Integer(), nullable=True),
        sa.Column("default_system_prompt_id", sa.Integer(), nullable=True),
        sa.Column("default_user_profile_id", sa.Integer(), nullable=True),
        sa.Column("default_avatar_image", sa.String(), nullable=True),
        sa.CheckConstraint("id = 1", name="application_settings_singleton"),
        sa.ForeignKeyConstraint(
            ["default_ai_model_id"],
            ["aiModel.id"],
        ),
        sa.ForeignKeyConstraint(
            ["default_system_prompt_id"],
            ["systemPrompt.id"],
        ),
        sa.ForeignKeyConstraint(
            ["default_user_profile_id"],
            ["userProfile.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "chatSession",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("character_id", sa.Integer(), nullable=False),
        sa.Column("user_profile_id", sa.Integer(), nullable=False),
        sa.Column("ai_model_id", sa.Integer(), nullable=False),
        sa.Column("system_prompt_id", sa.Integer(), nullable=False),
        sa.Column("pre_prompt", sa.Text(), nullable=True),
        sa.Column("pre_prompt_enabled", sa.Boolean(), nullable=False),
        sa.Column("post_prompt", sa.Text(), nullable=True),
        sa.Column("post_prompt_enabled", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["ai_model_id"], ["aiModel.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["character_id"], ["character.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["system_prompt_id"], ["systemPrompt.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["user_profile_id"], ["userProfile.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "message",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chat_session_id", sa.Integer(), nullable=False),
        sa.Column(
            "role", sa.Enum("USER", "ASSISTANT", name="messagerole"), nullable=False
        ),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["chat_session_id"], ["chatSession.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("message")
    op.drop_table("chatSession")
    op.drop_table("applicationSettings")
    op.drop_table("userProfile")
    op.drop_table("systemPrompt")
    op.drop_table("character")
    op.drop_table("aiModel")
    # ### end Alembic commands ###
