"""add_first_messages_and_initialization_support_v2

Revision ID: dda9107eac76
Revises: d69c0aed44a2
Create Date: 2025-05-28 13:04:19.199038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dda9107eac76'
down_revision: Union[str, None] = 'd69c0aed44a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Skip first_messages as it's already added by a previous migration
    # op.add_column('character', sa.Column('first_messages', sa.JSON(), nullable=True))
    op.add_column('chatSession', sa.Column('first_message_initialized', sa.Boolean(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chatSession', 'first_message_initialized')
    # Skip first_messages as it should remain from previous migration
    # op.drop_column('character', 'first_messages')
    # ### end Alembic commands ###
